name: currency_decimal_formatter
description: >-
  Currency TextField formatter and utilities for converting between text and currency
  amounts.
version: 0.0.8
homepage: https://github.com/yuriescl/flutter_currency_decimal_formatter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0
  decimal: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

